name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest --disable-warnings

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure SSH Directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H 16.16.25.254 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        env:
          SSH_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
        run: |
          # Add private key for SSH
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          # Sync files to the target directory, excluding local venv
          echo "Deploying files to EC2..."
          rsync -avz --delete --exclude 'venv/' -e "ssh -i deploy_key.pem" ./ ubuntu@16.16.25.254:~/fastapi-book-project

          # Automate virtual environment setup and restart FastAPI
          echo "Setting up virtual environment and starting FastAPI..."
          ssh -i deploy_key.pem ubuntu@16.16.25.254 <<EOF
            cd ~/fastapi-book-project

            # Ensure virtual environment exists
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            # Activate virtual environment and install dependencies
            venv/bin/pip install --upgrade pip
            venv/bin/pip install -r requirements.txt

            # Restart FastAPI application using the virtual environment
            pkill -f 'uvicorn' || true
            nohup venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ~/fastapi-book-project > fastapi.log 2>&1 &
          EOF

          echo "Deployment complete!"
