name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest --disable-warnings

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh  # Ensure .ssh directory exists
          ssh-keyscan -H 16.16.25.254 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts  # Set correct permissions

      - name: Deploy to AWS EC2
        env:
          SSH_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          # Test SSH connection
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ubuntu@16.16.25.254 "echo 'Connected to server'"

          # Ensure target directory exists in the user's home directory
          ssh -i deploy_key.pem ubuntu@16.16.25.254 "mkdir -p ~/fastapi-book-project"

          # Copy files to the server (only directory contents)
          scp -i deploy_key.pem -r ./* ubuntu@16.16.25.254:~/fastapi-book-project

          # Start FastAPI application
          ssh -i deploy_key.pem ubuntu@16.16.25.254 "
            pkill -f 'uvicorn' || true  # Stop any running instance of uvicorn
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ~/fastapi-book-project &  # Start FastAPI in the background
          "
